### ISSUE TITLE
missing dependencies:  blots/block/embed

### ISSUE THREAD

**Issue by zwaldeck** [ayush013/ngx-quill-upload#1]
Hi,

There seem to be some dependencies missing. Or am I missing something?

`ERROR in The target entry-point "ngx-quill-upload" has missing dependencies:
 - blots/block/embed`

` "dependencies": {
    "@angular/animations": "~10.0.5",
    "@angular/common": "~10.0.5",
    "@angular/compiler": "~10.0.5",
    "@angular/core": "~10.0.5",
    "@angular/forms": "~10.0.5",
    "@angular/platform-browser": "~10.0.5",
    "@angular/platform-browser-dynamic": "~10.0.5",
    "@angular/router": "~10.0.5",
    "ngx-quill": "^12.0.1",
    "ngx-quill-upload": "^1.0.3",
    "quill": "^1.3.7",
    "quill-image-resize": "^3.0.9",
    "quill-image-resize-module": "^3.0.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },`

**Comment by ayush013** [comment]
Hi @zwaldeck 'blots/block/embed' is supposed to be imported from the Quill itself. Apparently this was a false warning and has been fixed [now](https://github.com/ayush013/ngx-quill-upload/releases/tag/1.0.6)

**Comment by zwaldeck** [comment]
@ayush013 Thanks for the quick response & update.

It works now!
