### ISSUE TITLE
When click on video Icon it still shows input filed to embed URL after register ngx-quill videoHandler

### ISSUE THREAD

**Issue by anwarulislam** [ayush013/ngx-quill-upload#10]
I've registered videoHandler to upload video using ngx-quill and ngx-quill-upload but it still shows embed url field instead of upload modal.

![image](https://user-images.githubusercontent.com/26295990/120975486-17e5fb00-c793-11eb-8733-bd5a9bd7dd10.png)

**Comment by ayush013** [comment]
Hi @anwarulislam, Did you get a console message saying that the plugin was over-written? If yes, what version on Angular/quill are you using

**Comment by ayush013** [comment]
Closing ticket due to inactivity
