### ISSUE TITLE
Feature Request: A way to delete the image

### ISSUE THREAD

**Issue by zwaldeck** [ayush013/ngx-quill-upload#2]
It would be nice to have an option to execute some code when an image/video is deleted.

**Comment by ayush013** [comment]
@zwaldeck One blocker I can think of is that it'll break the Quill's native undo/redo functionality. Probably this shouldn't be a part of this plugin but a separate package of its own kind.

**Comment by mdathersajjad** [comment]
@zwaldeck check blotformatter package, https://www.npmjs.com/package/quill-blot-formatter. My team used this to implement delete action as well as other actions.

**Comment by zwaldeck** [comment]
@mdathersajjad Looks really usefull thanks!
