### ISSUE TITLE
Bug :: Problem will come multiple image uploads

### ISSUE THREAD

**Issue by mdathersajjad** [ayush013/ngx-quill-upload#4]
@ayush013 thanks for this package. I implemented quill image upload by following this package, i found one issue with this library. you are storing the current handlerId as

>>
this.handlerId = this.helpers.generateID();
https://github.com/ayush013/ngx-quill-upload/blob/master/src/handlers/BaseHandler.ts#L87> 
if you try to upload multiple images this.handlerId will reference the latest generated id. You can see this by reducing the connection speed in dev tools to slow 3g so that it can be debugged.

**Comment by ayush013** [comment]
Hi, thanks for reporting. i just checked and seems like the reference is getting updated. I will see what can be done
